[package]
name = "spark-1"
version = "0.1.0"
edition = "2021"
description = "The spark package manager"

[dependencies]
clap = { version = "4.3.0", features = ["cargo"] }
clap_generate = "3.0.3"
termion = "2.0.1"
spark= { path = "./spark" }
